### ISSUE TITLE
phase 3: Rotation of the active piece

### ISSUE THREAD

**Issue by ozkriff** [sumproxy/tetris#3]
Controls: 'R' - rotate

**Comment by sumproxy** [comment]
For the sake of clarification, do you mean it will rotate in one direction?

**Comment by ozkriff** [comment]
yep, clockwise

**Comment by sumproxy** [comment]
Fixed via https://github.com/sumproxy/tetris/commit/ed2c02b5a1abd634a4ef03033c53597418e8a851
